model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    beta_schedule: cosine
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: lr_image
    image_size: 512
    channels: 3
    concat_mode: true
    cond_stage_trainable: false
    unet_config:
      target: ldm.modules.diffusionmodules.imagenmodel.EfficientUNetModel
      params:
          in_channels: 6
          out_channels: 3
          model_channels: 192
          attention_resolutions: [32, 16]
          num_res_blocks: [1, 2, 3, 4]
          channel_mult: [1, 2, 3, 4]
          num_heads: 8
          resblock_updown: true
          context_dim: 768
          checkpoint: fairscale
          skip_rescale: false
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config:
      target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: false
    num_workers: 24
    train:
      target: ldm.data.avid.AvidSuperResTrain
      params:
        size: 512
        degradation: bsrgan_light
        downscale_f: 4
        min_crop_f: 0.1
        max_crop_f: 0.25
    validation:
      target: ldm.data.avid.AvidSuperResValidation
      params:
        size: 512
        degradation: bsrgan_light
        downscale_f: 4
        min_crop_f: 0.1
        max_crop_f: 0.25
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        increase_log_steps: false
        max_images: 4
        clamp: true
        log_images_kwargs:
          plot_diffusion_rows: true
          plot_progressive_rows: false
          inpaint: false
  modelcheckpoint:
    params:
      every_n_train_steps: 2000
  trainer:
    benchmark: True
    max_epochs: -1
    precision: 16
    strategy: fsdp